### ISSUE TITLE
Investigate whether to use OpenJDK

### ISSUE THREAD

**Issue by SubJunk** [UniversalMediaServer/UniversalMediaServer#1853]
Now that we include JRE in our bundles, it may be good to see if there are any advantages to using OpenJDK instead.

We already run our automated tests on that on the Linux Travis builds.

**Comment by David-Else** [comment]
I am not sure the bundling of Java is such a great idea. I have been using `java-1.8.0-openjdk` and UMS with no problems for at least a year in Fedora. I can trust that version, and it is integrated into the system with all the right security settings for things like SELinux.

What if there is a security patch for Java that needs urgent installation? There is no repo for UMS, so we would never know and keep on running the old version.

A simple readme that shows how to install java-1.8.0-openjdk in each distro would make bundling it not needed, and all the security risks are gone.

https://openjdk.java.net/install/

> JDK 8
> Debian, Ubuntu, etc.
> 
> On the command line, type:
> 
>     $ sudo apt-get install openjdk-8-jre
> 
> The openjdk-8-jre package contains just the Java Runtime Environment. If you want to develop Java programs then please install the openjdk-8-jdk package.
> Fedora, Oracle Linux, Red Hat Enterprise Linux, etc.
> 
> On the command line, type:
> 
>     $ su -c "yum install java-1.8.0-openjdk"
> 
> The java-1.8.0-openjdk package contains just the Java Runtime Environment. If you want to develop Java programs then install the java-1.8.0-openjdk-devel package.

How can I use my own version of Java in version 9? Can I change a setting? Thanks!

**Comment by SubJunk** [comment]
On Linux, UMS will fallback to the system Java if the UMS one isn't there, so you can simply remove the folder in UMS

**Comment by David-Else** [comment]
@SubJunk Thanks! That works, so now I have 9.0.1 booting up, but for some reason I can't seem to get UMS to work on Centos 8, and it worked great on Fedora 28 that Centos is built from.

I can browse the media OK in the local web browser at `http://192.168.0.2:9001` but it does not show up on any devices on the network. I am not an expert at networking, but I think this shows the status of the firewall:

```
firewall-cmd --get-active-zones
public
  interfaces: eno1

firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eno1
  sources: 
  services: cockpit dhcpv6-client ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
And UMS mentions:
```
10:44:36 INFO  Using address /192.168.0.2 found on network interface: name:eno1 (eno1)
10:44:36 INFO  Created socket: /192.168.0.2:5001
```
Sorry to ask here, but I searched the Linux area of the UMS forum and found nothing. I can find no mention of Linux firewall settings in the docs, I assume Centos is more secure by default and blocking something. Cheers!
