### ISSUE TITLE
UMS on docker not discoverable and can't find renderers

### ISSUE THREAD

**Issue by gauravsuman007** [UniversalMediaServer/UniversalMediaServer#3829]
I'm running UMS in docker using the following docker-compose file (note that I'm not using network mode as host)

```
version: '3.7'

services:

  universalmediaserver:

    image: universalmediaserver/ums
    container_name: ums
#    network_mode: host
    ports :
      - 9002:9001
      - 9003:9002
      - 1044:1044
      - 5001:5001
      - 5002:5002
      - 1900:1900
    environment:
      - UMS_PROFILE=/profile
      
    volumes:
      - ./profile:/profile
      - /media/hellonfire/Bhandaar/Music:/root/media:ro

    restart: always
```

Note that my port 9001 was already occupied by another app so I decided to remap that to 9002 ans similarly for 9002->9003

I can play content using the web UI but I can't find any renderers in the web UI. I can see my Sony hometheatre as a renderer on my phone using an app but it doesn't show up on UMS

Additionally, I can't see the UMS on my local network as a DLNA server.

Is this a problem with the port list? Do I need to map additional ports?

**Comment by ik666** [comment]
Since you're not using network mode you need to "route" multicast packets with some special software like upnp-proxy ... ports 9001 and 9002 are used and should be mapped.

I think it's easier to just use network mode and omit the port configuration. In network mode, ports 9001 and 9002 would be used by default, therefore manually editing the UMF.conf config file is necessary.

**Comment by gauravsuman007** [comment]
Thanks for the replies.

First to clarify docker's networking, it's essentially a NAT and I find the docker port remapping to be easier to manipulate than the UMS.conf as I know that all my config changes are in the docker-compose file and I don't need to take care of any other file (that's my docker philosophy)

So that leaves the question of whether my port configuration is complete. I see from @ik666 's comment that there might be some multicast considerations that may be getting lost in my port (re)mapping. Can you tell me which ports are these? I see you mentioned the ports 9001 and 9002. I was under the impression that these are just for the webUI and the web player so can be safely remapped. Can you comment on this?

**Comment by gauravsuman007** [comment]
I checked a bit more on UDP broadcast and figured that docker's default network bridge mode doesn't allow it.

So I chose to create a separate network with ipvlan (could have used macvlan but I wanted an L2 bridge instead of L3 provided by macvlan)
```
docker network create -d ipvlan \
    --subnet=192.168.2.0/24 \
    --gateway=192.168.2.1 \
     -o ipvlan_mode=l2 -o parent=eno1 ums_network
```

And now here's my updated docker-compose file
```
version: '3.7'

services:
  universalmediaserver:
    image: universalmediaserver/ums
    container_name: ums
    networks:
      ums_network:
        ipv4_address: 192.168.2.237
    environment:
      - UMS_PROFILE=/profile
    volumes:
      - ./profile:/profile
      - /media/hellonfire/Bhandaar/Music:/root/media:ro
    restart: always

networks:
  ums_network:
    external: true
```

Now I can see all my renderers in UMS web UI and can browse the content shared from UMS on other devices.

**I think this should probaböy be added to the official docker documentation**
